quarkus.http.port=9091
quarkus.application.name=api-gateway

quarkus.grpc.clients.document-service.host=localhost
%docker.quarkus.grpc.clients.document-service.host=host.docker.internal
quarkus.grpc.clients.document-service.port=8080
quarkus.grpc.clients.document-service.plain-text=true

quarkus.container-image.build=true
quarkus.container-image.name=api-gateway
quarkus.container-image.group=sagargrovetech

consul.host=localhost
%docker.consul.host=host.docker.internal
consul.port=8500


quarkus.stork.document-service.service-discovery.type=consul
quarkus.stork.document-service.service-discovery.consul-host=localhost
%docker.quarkus.stork.document-service.service-discovery.consul-host=host.docker.internal
quarkus.stork.document-service.service-discovery.consul-port=8500
quarkus.grpc.clients.document-service.stork.enabled=true


quarkus.oidc.auth-server-url=http://localhost:8180/realms/secure-docs
%docker.quarkus.oidc.auth-server-url=http://host.docker.internal:8180/realms/secure-docs
quarkus.oidc.client-id=secure-docs-client
quarkus.oidc.credentials.secret=0w39aIdj7RloFBLqWrIxqGXOZ8HrO1O7
quarkus.oidc.token-issuer=http://localhost:8180/realms/secure-docs

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true

#quarkus.rest-client.document-service.url=http://localhost:8080
#quarkus.rest-client.document-service.scope=jakarta.inject.Singleton

# gRPC Configuration
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.enable-plain-text=true
quarkus.grpc.server.enable-ssl=false
quarkus.grpc.auth.enabled=true
quarkus.grpc.server.use-separate-server=false